// Public send surface: the browser calls `sendMessage` to post a user turn.
//
// Flow (matches docs/ARCHITECTURE.md step 2):
//   1. Verify the authenticated user owns the chat.
//   2. Idempotency: if this (user, clientMessageId) was already accepted, return
//      the original ids without re-inserting or re-dispatching.
//   3. Verify the caller owns every attachment storageId (IDOR defense).
//   4. Insert an optimistic `user` message (status "complete") so it renders
//      immediately and reactively.
//   5. Insert an `outbox` row (status "pending") describing the work.
//   6. Schedule `bridge.dispatch` (internalAction) to push it to the bridge.
//
// The actual gateway dispatch happens in the scheduled internalAction
// (`convex/bridge.ts`) because mutations cannot do `fetch`. Secrets used to
// reach the bridge live only in deployment env, never here or in the browser.

import { v } from "convex/values";
import { mutation, MutationCtx } from "./_generated/server";
import { internal } from "./_generated/api";
import { Id } from "./_generated/dataModel";
import { requireActive, requireOwnedChat } from "./lib/access";
import { auditImpersonated } from "./lib/audit";
import { assertOwnsUpload } from "./uploads";
import { writeTraceEvent } from "./observability";
import { recordFileForPart } from "./lib/files";
import { isChatBusy, countQueued, MAX_QUEUED_PER_CHAT } from "./lib/outboxQueue";
import { QUEUED_ORDER_SENTINEL } from "./lib/messageOrder";
import { QUOTE_EXCERPT_CAP } from "./lib/quoteReply";
import { requireAgentMembership } from "./chats";
import { resolveTargetForTurn } from "./routing";

export const sendMessage = mutation({
  args: {
    chatId: v.id("chats"),
    text: v.string(),
    // Client-generated idempotency key (e.g. crypto.randomUUID()). REQUIRED: a
    // mutation can be retried transparently by the Convex client on a transient
    // failure, so the same logical send may arrive more than once. We dedupe on
    // (userId, clientMessageId) to guarantee exactly one user message + one
    // dispatch per logical send.
    clientMessageId: v.string(),
    // Attachments the browser already uploaded via
    // `ctx.storage.generateUploadUrl()`. Each carries the storage id plus the
    // browser-known filename/mimeType so the rendered part is accurate. Each
    // storageId MUST have been registered to this user (see uploads.ts);
    // otherwise it is rejected as an IDOR attempt.
    attachments: v.optional(
      v.array(
        v.object({
          storageId: v.id("_storage"),
          filename: v.string(),
          mimeType: v.string(),
          // "pasted" = auto-generated by the composer's large-paste guard;
          // recorded on the files row so Settings › Files can hide it by default.
          origin: v.optional(v.literal("pasted")),
        }),
      ),
    ),
    // MULTI-AGENT per-turn router: the agent the user addressed THIS turn to. Absent =
    // the chat's primary agent (the unchanged single-agent path). The composer sends it
    // only for a deliberate per-turn agent choice; the dispatch authorizes it at the
    // trust boundary (resolveTargetForTurn) and stamps it for per-message attribution.
    routedAgent: v.optional(
      v.object({ instanceName: v.string(), agentId: v.string() }),
    ),
    // QUOTE-REPLY: the assistant block this turn replies to ("here is what I am
    // responding to"). The EXCERPT was captured client-side at click time; the
    // dispatch prefixes the outgoing text with the resolved quote_reply
    // injection. blockIndex null = the whole quoted message.
    quote: v.optional(
      v.object({
        messageId: v.id("messages"),
        blockIndex: v.union(v.number(), v.null()),
        excerpt: v.string(),
      }),
    ),
  },
  handler: async (ctx, args) => {
    const { userId, actor } = await requireActive(ctx);
    const chat = await requireOwnedChat(ctx, userId, args.chatId);

    // 2. Idempotency short-circuit. Run BEFORE any insert so a retry inserts
    //    neither a duplicate message nor a duplicate outbox row, and does not
    //    re-schedule the dispatch. Scoped by userId so one user's client ids
    //    can never collide with another's.
    const existing = await ctx.db
      .query("outbox")
      .withIndex("by_client_message", (q) =>
        q.eq("userId", userId).eq("clientMessageId", args.clientMessageId),
      )
      .unique();
    if (existing !== null) {
      // Trace the deduped retry (metadata only — never args.text). Defensive:
      // a trace failure must NEVER turn a successful idempotent send into an
      // error, so the write is wrapped and swallowed.
      await traceSend(ctx, {
        userId,
        chatId: args.chatId,
        textLen: args.text.length,
        attachmentCount: (args.attachments ?? []).length,
        deduped: true,
        outboxId: existing._id,
      });
      return {
        messageId: existing.messageId ?? null,
        outboxId: existing._id,
        deduped: true as const,
      };
    }

    const now = Date.now();
    const attachments = args.attachments ?? [];

    // 2c. PER-TURN ROUTE VALIDATION AT THE SOURCE. The routedInstanceName this
    //     mutation stamps on the user message is what the ingest authorization's
    //     per-turn branch TRUSTS (chatAllowsInstance) — so it must never hold
    //     raw client input. Validate against the user's effective agent set NOW
    //     (the same gate createChat applies to a chat binding); a forged/revoked
    //     routedAgent fails the send immediately instead of stamping a route the
    //     dispatch would only reject later (codex P1).
    if (args.routedAgent !== undefined) {
      await requireAgentMembership(
        ctx,
        userId,
        args.routedAgent.instanceName,
        args.routedAgent.agentId,
      );
      // AND the route must be DISPATCHABLE right now — the same resolution the
      // dispatch applies. A granted-but-gone agent (deleted on the gateway,
      // userAgents row lingering) would stamp a provenance the dispatch then
      // rejects as no_agent, leaving a valid-looking route that never ran
      // (codex P1). Refuse at the source instead.
      const resolved = await resolveTargetForTurn(
        ctx,
        chat,
        userId,
        args.routedAgent,
      );
      if (resolved.target === null) {
        throw new Error("Forbidden: routed agent is not dispatchable");
      }
    }

    // 2b. Mid-turn serialization (Phase 1: QUEUE). If the chat already has a turn
    //     IN FLIGHT, this send is parked as a `queued` outbox row and the drainer
    //     dispatches it (FIFO) once the current turn ends — the bridge is strictly
    //     one-turn-per-session, so we never dispatch two turns to a chat at once.
    //     An idle chat dispatches immediately (the historical behavior). Computed
    //     BEFORE any insert so the busy-check (and Convex's serializable read set)
    //     reflects only PRIOR turns, not this row.
    const busy = await isChatBusy(ctx, chat._id);
    if (busy && (await countQueued(ctx, chat._id)) >= MAX_QUEUED_PER_CHAT) {
      // Bounded queue: refuse a runaway backlog with a clear, catchable error
      // (the composer surfaces it as a toast). Thrown before any write, so the
      // transaction rolls back cleanly — no orphan message/outbox row.
      throw new Error("QUEUE_FULL");
    }

    // 3. IDOR defense: every attachment must be a blob THIS user uploaded.
    //    `assertOwnsUpload` throws (aborting the whole mutation) on any id that
    //    was not registered to the caller, so we never attach someone else's
    //    storage blob to a message.
    for (const attachment of attachments) {
      await assertOwnsUpload(ctx, userId, attachment.storageId);
    }

    // 3b. QUOTE-REPLY guards: the quoted message must belong to THIS chat
    //     (cross-chat/IDOR — same rule as chatBookmarks.toggleBookmark), the
    //     excerpt is server-bounded, and the block index must be a small
    //     non-negative integer. A deleted quoted message rejects cleanly (the
    //     UI cannot offer a quote on a message it no longer renders).
    let quote: { messageId: Id<"messages">; blockIndex: number | null; excerpt: string } | null =
      null;
    if (args.quote !== undefined) {
      const quoted = await ctx.db.get(args.quote.messageId);
      if (quoted === null || quoted.chatId !== chat._id) {
        throw new Error("Invalid: quoted message not in this chat");
      }
      // Only an ASSISTANT answer can be quoted (the feature's contract: "here
      // is the passage of YOUR reply I am responding to") — a direct caller
      // must not persist a quote of a user/system row (codex P2).
      if (quoted.role !== "assistant") {
        throw new Error("Invalid: quoted message is not an assistant reply");
      }
      const excerpt = args.quote.excerpt.trim().slice(0, QUOTE_EXCERPT_CAP);
      if (excerpt.length === 0) throw new Error("Invalid: empty quote excerpt");
      const blockIndex = args.quote.blockIndex;
      if (
        blockIndex !== null &&
        (!Number.isInteger(blockIndex) || blockIndex < 0 || blockIndex > 10_000)
      ) {
        throw new Error("Invalid: quote block index");
      }
      quote = { messageId: args.quote.messageId, blockIndex, excerpt };
    }

    // 4. Optimistic user message (immediately visible & reactive). A QUEUED follow-up
    //    carries a SENTINEL orderTime so it sorts AFTER the in-flight turn (and its
    //    not-yet-created assistant reply) — drainNextQueued re-stamps it to the real
    //    dispatch time when this turn is promoted. Idle sends keep _creationTime order.
    const messageId = await ctx.db.insert("messages", {
      chatId: chat._id,
      userId,
      role: "user",
      status: "complete",
      text: args.text,
      updatedAt: now,
      ...(busy ? { orderTime: QUEUED_ORDER_SENTINEL } : {}),
      // Per-turn routing: record which agent this user turn is addressed to (drives the
      // per-message agent chip + the composer's "last-used agent" default).
      ...(args.routedAgent
        ? {
            routedInstanceName: args.routedAgent.instanceName,
            routedAgentId: args.routedAgent.agentId,
          }
        : {}),
      // Quote-reply anchor + display excerpt (the prompt preamble is composed
      // at dispatch/rehydration — `text` stays the user's clean instruction).
      ...(quote
        ? {
            quotedMessageId: quote.messageId,
            ...(quote.blockIndex !== null
              ? { quotedBlockIndex: quote.blockIndex }
              : {}),
            quotedExcerpt: quote.excerpt,
          }
        : {}),
    });

    // Attach uploaded files as ordered parts on the user message so they render
    // in the thread, preserving the browser-supplied filename/mimeType.
    let order = 0;
    for (const attachment of attachments) {
      const part = {
        kind: "file" as const,
        storageId: attachment.storageId,
        filename: attachment.filename,
        mimeType: attachment.mimeType,
      };
      await ctx.db.insert("messageParts", { messageId, order: order++, part });
      // Paired files-row write (invariant): an inbound user upload is listable in
      // Settings → Fichiers immediately, NOT gated on the assistant's reply.
      await recordFileForPart(ctx, {
        messageId,
        chatId: chat._id,
        userId,
        direction: "inbound",
        instanceName: chat.instanceName,
        part,
        createdAt: now,
        origin: attachment.origin,
      });
    }

    // Keep the chat sorted-to-top.
    await ctx.db.patch(chat._id, { updatedAt: now });

    // 5. Outbox row describing the pending dispatch. `messageId` is stored so a
    //    deduped retry can return the original message id (see step 2).
    const outboxId = await ctx.db.insert("outbox", {
      chatId: chat._id,
      userId,
      clientMessageId: args.clientMessageId,
      messageId,
      text: args.text,
      attachmentIds: attachments.map((a) => a.storageId),
      // Keep filename + mimeType so the dispatch can build OpenClaw's
      // chat.send.attachment shape (the storageId alone loses them).
      attachments: attachments.map((a) => ({
        storageId: a.storageId,
        filename: a.filename,
        mimeType: a.mimeType,
      })),
      // Busy chat → park as `queued` (the drainer dispatches it later); idle chat
      // → `pending` and dispatch now.
      status: busy ? "queued" : "pending",
      // Per-turn routing target, read back by the dispatch.
      ...(args.routedAgent ? { routedAgent: args.routedAgent } : {}),
      // Quote-reply: the dispatch (and any redo) prefixes the text with the
      // resolved quote_reply injection filled with this excerpt.
      ...(quote ? { quotedExcerpt: quote.excerpt } : {}),
    });

    // 6. Schedule the dispatch ONLY for an idle chat. A queued row is dispatched
    //    by drainNextQueued when the in-flight turn ends (finalize / failed /
    //    stuck-stream reconcile). Cannot fetch from a mutation, hence the schedule.
    if (!busy) {
      await ctx.scheduler.runAfter(0, internal.bridge.dispatch, { outboxId });
    }

    // Audit a send performed under impersonation. PHI: we log the message id
    // ONLY — never `args.text` or attachment contents.
    await auditImpersonated(ctx, actor, "message.send", {
      resource: "message",
      resourceId: messageId,
    });

    // Trace the accepted outbound user turn (metadata only — never args.text).
    await traceSend(ctx, {
      userId,
      chatId: args.chatId,
      textLen: args.text.length,
      attachmentCount: attachments.length,
      deduped: false,
      outboxId,
    });

    return { messageId, outboxId, deduped: false as const };
  },
});

/**
 * Emit a `chat.send` trace (D2 metadata only). Wrapped so a trace failure can
 * NEVER abort the user-visible send mutation.
 *
 * correlationId = `${chatId}:${outboxId}` — there is no runId on the user turn
 * yet (the assistant run id is assigned later by the bridge), so we anchor the
 * turn on the outbox row that the dispatch/stream will be associated with.
 *
 * TODO(M8): the assistant half (stream.ts) keys on `${chatId}:${runId}`, so the
 * by_correlation index cannot follow a full turn end-to-end until the bridge
 * writes the learned runId back onto the outbox row (or echoes a shared
 * correlationId through startAssistant). Needs bridge wiring — deferred.
 */
async function traceSend(
  ctx: MutationCtx,
  args: {
    userId: Id<"users">;
    chatId: Id<"chats">;
    textLen: number;
    attachmentCount: number;
    deduped: boolean;
    outboxId: Id<"outbox">;
  },
): Promise<void> {
  try {
    await writeTraceEvent(ctx, {
      kind: "chat.send",
      direction: "outbound",
      principalType: "user",
      principalId: args.userId,
      chatId: args.chatId,
      correlationId: `${args.chatId}:${args.outboxId}`,
      meta: JSON.stringify({
        textLen: args.textLen,
        attachmentCount: args.attachmentCount,
        deduped: args.deduped,
        outboxId: args.outboxId,
      }),
    });
  } catch {
    // Best-effort: never break the primary send flow on a trace error.
  }
}
