import { isPastedFile } from "./pasteRouting";
import type {
  Attachment,
  AttachmentAdapter,
  CompleteAttachment,
  PendingAttachment,
} from "@assistant-ui/react";
import type { ConvexReactClient } from "convex/react";
import { api } from "./convexApi";
import type { Id } from "./convexApi";
import { isModelNativeMime } from "../../convex/lib/mediaTransport";
import {
  DEFAULT_GATEWAY_MAX_PAYLOAD,
  maxRawInboundBytes,
} from "../../convex/lib/attachmentLimits";
import { uploadProgressStore } from "./uploadProgressStore";
import { beginAttachmentAdd, endAttachmentAdd } from "./attachmentBusy";
import { m } from "@/paraglide/messages.js";

// Attachment adapter for assistant-ui that uploads files straight into Convex
// file storage via a short-lived signed upload URL, then carries the resulting
// `_storage` id (plus filename/mimeType) so `api.send.sendMessage` can attach
// it to the user message and the outbox row.
//
// Flow (Convex file upload pattern):
//   1) mutation api.chats.generateUploadUrl   -> uploadUrl
//   2) POST the raw bytes to uploadUrl         -> { storageId }

/** Text-like uploads carry an explicit charset so the blob, re-served verbatim
 *  by Convex storage, renders as UTF-8 when opened in a tab (not Latin-1). */
function uploadContentType(mimeType: string): string {
  const base = mimeType.split(";")[0]?.trim().toLowerCase() ?? "";
  const textLike =
    base.startsWith("text/") ||
    base === "application/json" ||
    base === "application/xml" ||
    base === "image/svg+xml";
  if (!textLike || mimeType.toLowerCase().includes("charset")) return mimeType;
  return `${mimeType}; charset=utf-8`;
}

//   3) mutation api.uploads.registerUpload     -> record ownership (IDOR gate)
//   4) keep {storageId, filename, mimeType}    -> read by onNew/sendMessage
//
// The browser never sees a server filesystem path; it only ever holds an opaque
// Convex storage id and a temporary signed URL. The upload URL is generated by
// an authenticated Convex mutation, so only the signed-in user can upload, and
// step 3 records that ownership so `sendMessage` can reject attachments the
// caller does not own.

/** Convex storage metadata stashed on the assistant-ui attachment. */
export interface ConvexAttachmentContent {
  storageId: string;
  filename: string;
  mimeType: string;
  /** "pasted" when the file was auto-generated from a large composer paste —
   *  Settings › Files hides those by default. Absent for real user files. */
  origin?: "pasted";
}

/** assistant-ui Attachment carrying our Convex storage metadata. */
export type ConvexAttachment = CompleteAttachment & {
  convex: ConvexAttachmentContent;
};

function makeId(): string {
  return `att_${Math.random().toString(36).slice(2)}_${Date.now()}`;
}

/**
 * Pull the full Convex attachment payloads out of a turn's attachments so
 * `onNew` can pass them to
 * `api.send.sendMessage({ attachments: [{ storageId, filename, mimeType }] })`.
 *
 * This replaces the old `attachmentStorageIds` (which returned a bare
 * `string[]` of storage ids) because `sendMessage` validates the richer
 * `{ storageId, filename, mimeType }[]` shape — passing bare ids fails arg
 * validation and also loses the filename/mimeType needed to render the file
 * part. Each entry's `storageId` is later re-typed to `Id<"_storage">` by the
 * generated mutation validator at the call site.
 */
export function attachmentParts(
  attachments: readonly Attachment[] | undefined,
): ConvexAttachmentContent[] {
  if (!attachments) return [];
  const parts: ConvexAttachmentContent[] = [];
  for (const a of attachments) {
    const convex = (a as Partial<ConvexAttachment>).convex;
    if (convex?.storageId) {
      parts.push({
        storageId: convex.storageId,
        filename: convex.filename,
        mimeType: convex.mimeType,
        ...(convex.origin ? { origin: convex.origin } : {}),
      });
    }
  }
  return parts;
}

export function createConvexAttachmentAdapter(
  convex: ConvexReactClient,
  // Surface a rejection (e.g. too large) as a VISIBLE toast — assistant-ui only
  // logs a thrown add() error, so without this the user gets no reason. Optional
  // so non-UI callers/tests can omit it.
  onReject?: (message: string) => void,
  // The current chat, so add() can resolve the routed instance's INBOUND policy:
  // a tool-read file on a shared-fs instance rides by reference (any size), so the
  // inline maxPayload cap must NOT block it. Null/omitted → inline cap only.
  chatId?: string | null,
  // The agent the COMPOSER currently targets (per-turn routing), read at add()
  // time — the upload cap must be the TARGET gateway's frame limit, not the last
  // send's (a switch to an agent on another instance changes the cap).
  getRoutedAgent?: () => { instanceName: string; agentId: string } | null,
): AttachmentAdapter {
  return {
    // "*" is assistant-ui's "no restriction" sentinel: the composer then omits
    // the <input accept> attribute entirely, so the OS picker greys out NOTHING
    // (docx/xlsx/zip/… all selectable). Safe end-to-end: sendMessage validates
    // mimeType as a plain string, the bridge passes bytes through verbatim and
    // the gateway offloads ANY inbound file to media/inbound for the agent's
    // tools — only images additionally feed vision. Size is the only gate, and it
    // is DERIVED from the gateway's maxPayload (see add(), via getBridgeAvailability).
    accept: "*",

    async add({ file }: { file: File }): Promise<PendingAttachment> {
      // Signal "an attachment is being added" for the whole async operation so a
      // detached-composer pin is refused while a file is still landing on the
      // runtime (codex re-review P1) — covers the native picker + file pastes,
      // not just the text-paste paths a component counter sees.
      beginAttachmentAdd();
      try {
      // Reject oversized files UPFRONT (before upload) using the limit DERIVED from
      // the gateway's maxPayload — no hardcoded size. The server reports it via
      // getBridgeAvailability.maxInboundBytes.
      let maxInboundBytes: number | null = null;
      try {
        const routedAgent = getRoutedAgent?.() ?? null;
        const avail = await convex.query(
          api.bridgeHealth.getBridgeAvailability,
          // Scope the inbound cap to THIS chat's gateway (one bridge, N gateways) —
          // and to the composer's CURRENT target when per-turn routing picked one
          // (validated server-side by the dispatch's own authorization).
          chatId
            ? { chatId: chatId as Id<"chats">, ...(routedAgent ? { routedAgent } : {}) }
            : {},
        );
        maxInboundBytes = avail?.maxInboundBytes ?? null;
      } catch {
        // Availability query failed -> treat the cap as unknown (handled below).
      }
      // When the real per-instance cap is NOT yet known (cold poll / availability
      // query failed) we DON'T fail open — we fall back to OpenClaw's own default
      // frame limit, the SAME conservative value the Convex dispatch uses. Failing
      // open here let an oversize upload sail past the composer to be rejected
      // downstream with a vague code (no upfront "trop volumineuse"); capping at the
      // default catches it here with the clear toast, and auto-corrects once the
      // bridge reports the real maxPayload.
      const inlineCap =
        maxInboundBytes ?? maxRawInboundBytes(DEFAULT_GATEWAY_MAX_PAYLOAD);
      // Transport-aware cap: a TOOL-READ file (not a Vision image) on a shared-fs
      // instance rides BY REFERENCE — the bridge streams it to a shared volume, so
      // it bypasses the inline maxPayload frame entirely. Use the (much larger)
      // shared-fs cap for those; images (model-native) still ride inline → capped.
      let effectiveCap = inlineCap;
      if (chatId && !isModelNativeMime(file.type)) {
        try {
          const policy = await convex.query(api.bridge.getChatInboundPolicy, {
            chatId: chatId as Id<"chats">,
          });
          if (policy?.inboundMediaMode === "shared-fs") {
            effectiveCap = policy.sharedFsMaxBytes;
          }
        } catch {
          // Policy unknown -> keep the inline cap; the server still enforces.
        }
      }
      if (file.size > effectiveCap) {
        const mb = (n: number) => Math.floor(n / 1024 / 1024);
        const message = m.attach_too_large({
          size: mb(file.size),
          max: mb(effectiveCap),
        });
        // Show the reason (toast); still throw so assistant-ui drops the file.
        onReject?.(message);
        throw new Error(message);
      }
      return {
        id: makeId(),
        type: inferAttachmentType(file.type),
        name: file.name,
        contentType: file.type || "application/octet-stream",
        file,
        status: { type: "running", reason: "uploading", progress: 0 },
      };
      } finally {
        endAttachmentAdd();
      }
    },

    async send(attachment: PendingAttachment): Promise<CompleteAttachment> {
      const file = attachment.file;
      // Surface progress IMMEDIATELY (0%) so the user sees the request register
      // the instant they hit send — the upload below is the slow part for a big
      // file, and it runs BEFORE onNew's optimistic echo. Cleared in `finally`
      // on success AND failure so a failed/cancelled upload never stays stuck.
      uploadProgressStore.report(attachment.id, 0, file.size || 1);
      try {
        // 1) One-time signed upload URL from an authenticated mutation.
        let uploadUrl: string;
        try {
          uploadUrl = await convex.mutation(api.chats.generateUploadUrl, {});
        } catch (err) {
          console.error("[attach] generateUploadUrl failed:", err);
          throw err;
        }

        // 2) Stream the bytes to Convex storage via XHR (vs fetch) so the upload
        //    PROGRESS is observable — the same signed POST + headers as before.
        const storageId = await new Promise<string>((resolve, reject) => {
          const xhr = new XMLHttpRequest();
          xhr.open("POST", uploadUrl);
          // Text-like types get an explicit charset: Convex storage re-serves
          // the stored Content-Type verbatim, and without a charset a text file
          // opened in a tab renders as Latin-1 (mojibake on accents).
          xhr.setRequestHeader(
            "Content-Type",
            uploadContentType(file.type || "application/octet-stream"),
          );
          xhr.upload.onprogress = (e) => {
            if (e.lengthComputable) {
              uploadProgressStore.report(attachment.id, e.loaded, e.total);
            }
          };
          xhr.onload = () => {
            if (xhr.status >= 200 && xhr.status < 300) {
              try {
                resolve(
                  (JSON.parse(xhr.responseText) as { storageId: string })
                    .storageId,
                );
              } catch (err) {
                reject(err);
              }
            } else {
              reject(new Error(`Upload failed (${xhr.status})`));
            }
          };
          xhr.onerror = () => {
            console.error("[attach] upload POST failed (network/CORS/CSP)");
            reject(new Error("Upload failed (network)"));
          };
          xhr.send(file);
        });

        // 3) Record ownership so `sendMessage` can enforce IDOR. There is no
        //    server-side upload-completed hook, so this client callback is the
        //    only point at which the (user, storageId) pair becomes known.
        await convex.mutation(api.uploads.registerUpload, {
          storageId: storageId as Id<"_storage">,
        });

        const result: ConvexAttachment = {
          id: attachment.id,
          type: attachment.type,
          name: attachment.name,
          contentType: attachment.contentType,
          status: { type: "complete" },
          content: [{ type: "text", text: file.name }],
          convex: {
            storageId,
            filename: file.name,
            mimeType: file.type || "application/octet-stream",
            ...(isPastedFile(file) ? { origin: "pasted" as const } : {}),
          },
        };
        return result;
      } finally {
        uploadProgressStore.clear(attachment.id);
      }
    },

    async remove(): Promise<void> {
      // Pending uploads are discarded client-side; orphaned storage rows (and
      // their `uploads` ownership records) are garbage-collected by a Convex
      // cron on the server (the browser lacks the service key and must never
      // delete storage directly).
    },
  };
}

function inferAttachmentType(mime: string): PendingAttachment["type"] {
  if (mime.startsWith("image/")) return "image";
  return "document";
}
