// CONTRACT FIXTURE — captured VERBATIM from a LIVE bridge `GET /capabilities`.
//
// GENERATED by scripts/refresh-capabilities-fixture.mjs — do not edit by hand. Only
// runtime identifiers are anonymised (instanceName/key/agentId: deployment env, not
// contract); every other byte is the real response, including the per-target capability
// record the bridge RESOLVED for that gateway version.
//
// WHY IT EXISTS (red-team finding P2-1): the app and bridge repos ship on separate cycles
// and cannot import each other, so each pins its capability list with its own tests — two
// self-referential pins cannot detect drift BETWEEN the repos. This captured body is the
// cross-repo anchor: capabilities.test.ts asserts the UI's contract PARTITIONS this
// manifest exactly (consumed + declared-not-consumed = the manifest), and
// convex/compat.test.ts normalizes this exact body. A bridge-side rename therefore lands
// as a red test here instead of a silently hidden control.
//
// TO REFRESH: point a bridge at a validated gateway and run
//   node scripts/refresh-capabilities-fixture.mjs --bridge <url>
// The live bench does it as part of a validation run, so the anchor tracks the version
// the bench actually validated rather than whichever one somebody last pasted.
//
// Source: bridge 0.68.12 / gateway 2026.7.1 — captured 2026-07-28
//
// Imported by TESTS ONLY (src + convex test suites) — never by app or deployed
// Convex code, so it adds zero runtime weight.

export const LIVE_CAPABILITIES_BODY = {
  "instanceName": null,
  "gatewayVersion": null,
  "capabilities": {
    "kind": "openclaw",
    "agentDiscovery": true,
    "abort": true,
    "history": false,
    "attachments": true,
    "media": true,
    "streaming": "both"
  },
  "bridgeVersion": "0.68.12",
  "buildVersion": null,
  "buildRevision": null,
  "rehydrationDefault": true,
  "turnSessionEcho": true,
  "protocolVersion": 2,
  "compat": {
    "bridgeVersion": "0.68.12",
    "protocolVersion": 2,
    "providers": {
      "openclaw": {
        "supportedRange": {
          "min": "2026.5.19",
          "maxValidated": "2026.7.1"
        },
        "validatedVersions": [
          "2026.5.19",
          "2026.6.1",
          "2026.6.5",
          "2026.6.10",
          "2026.6.11",
          "2026.7.1-beta.2",
          "2026.7.1-beta.5",
          "2026.7.1"
        ],
        "capabilities": {
          "knobThinkingLevel": "2026.5.19",
          "knobModel": "2026.5.19",
          "knobFastMode": "2026.6.5",
          "knobUnset": "2026.6.5",
          "agentFiles": "2026.6.5",
          "sessionCompact": "2026.6.5",
          "configDefaults": "2026.6.5",
          "messageToolRecovery": "2026.5.19",
          "agentsDiscovery": "2026.5.19",
          "abort": "2026.5.19",
          "mediaOutbound": "2026.5.19",
          "inboundAttachments": "2026.6.1",
          "subagents": "2026.5.19",
          "cronList": "2026.5.19",
          "cronManage": "2026.7.1-beta.2",
          "talk": "2026.7.1"
        }
      },
      "hermes": {
        "supportedRange": {
          "min": "0.18.0",
          "maxValidated": "0.18.2"
        },
        "validatedVersions": [
          "0.18.0",
          "0.18.2"
        ],
        "capabilities": {
          "abort": "0.18.0",
          "agentsDiscovery": "0.18.0",
          "agentFiles": "0.18.0",
          "mediaOutbound": "0.18.0"
        }
      }
    }
  },
  "protocol": {
    "vendoredVersion": "2026.7.1",
    "coverage": {
      "handled": 158,
      "ignored": 420,
      "gaps": 18,
      "gapList": [
        "ChatAbortedEvent.errorMessage",
        "ChatSendParams.expectedSessionRoutingContract",
        "ChatAbortParams.preserveSideRuns",
        "SessionOperationEvent.operationId",
        "SessionOperationEvent.operation",
        "SessionOperationEvent.phase",
        "SessionOperationEvent.sessionKey",
        "SessionOperationEvent.agentId",
        "SessionOperationEvent.ts",
        "SessionOperationEvent.completed",
        "SessionOperationEvent.reason",
        "SessionsResetParams.reason",
        "CronJobState.consecutiveErrors",
        "CronRunLogEntry.usage",
        "TaskSummary.progressSummary",
        "TalkClientToolCallResult.idempotencyKey",
        "TalkClientCreateResult.expiresAt",
        "TalkClientCreateResult.offerHeaders"
      ]
    },
    "drift": [],
    "driftOverflow": 0
  },
  "targets": [
    {
      "key": "agent3",
      "instanceName": "main",
      "provider": "openclaw",
      "agentId": "agent1",
      "gatewayVersion": "2026.7.1",
      "capabilities": {
        "knobThinkingLevel": true,
        "knobModel": true,
        "knobFastMode": true,
        "knobUnset": true,
        "agentFiles": true,
        "sessionCompact": true,
        "configDefaults": true,
        "messageToolRecovery": true,
        "agentsDiscovery": true,
        "abort": true,
        "mediaOutbound": true,
        "inboundAttachments": true,
        "subagents": true,
        "cronList": true,
        "cronManage": true,
        "talk": true
      }
    },
    {
      "key": "agent2",
      "instanceName": "inst2",
      "provider": "hermes",
      "agentId": "agent1",
      "gatewayVersion": null,
      "capabilities": {
        "abort": true,
        "agentsDiscovery": true,
        "agentFiles": true,
        "mediaOutbound": true,
        "inboundAttachments": true,
        "cronList": true,
        "cronManage": true,
        "subagents": true
      }
    }
  ]
} as const;
